### ISSUE TITLE
GSoC 2024 interest

### ISSUE THREAD

**Issue by octonawish-akcodes** [seldon-code/hari-plotter#21]
Hi @amritagos @MSallermann @HaoZeke I'm interested in these two project ideas:
- Hari-Plotter Enhancements and ASV Visuals
- Reworking Robbie with JAX or PyTorch

How can I get started with any guidance?

**Comment by HaoZeke** [comment]
Hi @octonawish-akcodes thanks for your interest. So for both of those projects we expect some more leg work and a concrete pull request for starters. You could try working on either one by running through some usage examples or reading through the associated papers. I should note however that we are likely to be funded for only one of the projects, and I would also recommend applying to more projects :)

I'm closing the issue as it isn't suitable as an issue, but we can continue discussing here.
